algoritmo "parouimparProc"
var
   n: inteiro
   procedimento par_impar(v: inteiro)
   inicio
         se (v%2=0) entao
            escreval("o numero ",v," e par")
         senao
              escreval("o numero ",v," e impar")
         fimse
   fimprocedimento
inicio
      escreva("Digite um numero: ")
      leia(n)
      par_impar(n)
               escreval("o valor de v e ",v)
         escreval("o valor de n e ",n)
fimalgoritmo
